import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{width: '100%', display:"flex", justifyContent: 'space-evenly'}} className='header-div'>
          <div style={{maxWidth: '90%', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '1rem'}}>
            <h1>Lorenzo Orsini</h1>
            <h2>Terapista a domicilio</h2>
            <p>Lorenzo professa come fisioterapista dal 2019</p>
          </div>
          <Image
            src="/next.svg"
            width={200}
            height={200}
            alt="logo"
          />
        </div>
      </main>
    </>
  )
}
